version: '3.8'
services:
  rayst3r:
    image: ${IMAGE_NAME}:${TAG}
    working_dir: /src
    command: ["uvicorn", "eval_server:app", "--host", "0.0.0.0", "--port", "6000"]
    init: true
    tty: true
    restart: on-failure
    runtime: nvidia
    environment:
    - LOCAL_USER_ID=1000
    - LC_ALL=C.UTF-8
    - GLOG_minloglevel=2
    - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CUDA_ARCH: ${CUDA_ARCH}
    volumes:
      - ./:/src
    ports:
    - "6000:6000"
